# Generated by Django 2.1.5 on 2019-02-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190218_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
